<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bloom Haven - Flower Shop</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f9f9f9;
        }
        header {
            background-color: #ff6f61;
            color: white;
            padding: 1rem;
            text-align: center;
        }
        nav {
            display: flex;
            justify-content: center;
            background-color: #fff;
            padding: 0.5rem;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        nav a {
            margin: 0 1rem;
            text-decoration: none;
            color: #ff6f61;
            font-weight: bold;
        }
        nav a:hover {
            color: #ff3b2e;
        }
        .hero {
            text-align: center;
            padding: 2rem;
            background: url('flowers-hero.jpg') no-repeat center center/cover;
            color: white;
        }
        .hero h1 {
            font-size: 3rem;
            margin: 0;
        }
        .section {
            padding: 2rem;
            text-align: center;
        }
        .section h2 {
            margin-bottom: 1rem;
            color: #333;
        }
        .section p {
            color: #555;
        }
        .products {
            display: flex;
            justify-content: center;
            flex-wrap: wrap;
            gap: 2rem;
        }
        .product {
            background-color: #fff;
            padding: 1rem;
            border: 1px solid #ddd;
            border-radius: 8px;
            width: 300px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        .product img {
            width: 100%;
            border-radius: 8px;
        }
        .product h3 {
            margin: 1rem 0 0.5rem;
            color: #333;
        }
        .product p {
            color: #555;
        }
        footer {
            background-color: #333;
            color: white;
            text-align: center;
            padding: 1rem;
        }
    </style>
</head>
<body>
    <header>
        <h1>Bloom Haven</h1>
        <p>Your trusted flower shop for all occasions</p>
    </header>
    <nav>
        <a href="#about">About Us</a>
        <a href="#products">Our Products</a>
        <a href="#contact">Contact</a>
    </nav>
    <div class="hero">
        <h1>Fresh Flowers Delivered Daily</h1>
        <p>Brighten someone's day with a beautiful bouquet.</p>
    </div>
    <section id="about" class="section">
        <h2>About Us</h2>
        <p>At Bloom Haven, we specialize in creating stunning floral arrangements for every occasion. Whether you're celebrating a wedding, birthday, or just want to show someone you care, we've got you covered.</p>
    </section>
    <section id="products" class="section">
        <h2>Our Products</h2>
        <div class="products">
            <div class="product">
                <img src="bouquet1.jpg" alt="Bouquet of Roses">
                <h3>Classic Rose Bouquet</h3>
                <p>A timeless arrangement of fresh roses.</p>
            </div>
            <div class="product">
                <img src="bouquet2.jpg" alt="Wildflower Arrangement">
                <h3>Wildflower Wonder</h3>
                <p>A vibrant mix of seasonal wildflowers.</p>
            </div>
            <div class="product">
                <img src="bouquet3.jpg" alt="Tulip Basket">
                <h3>Tulip Delight</h3>
                <p>Bright and cheerful tulips in a charming basket.</p>
            </div>
        </div>
    </section>
    <section id="contact" class="section">
        <h2>Contact Us</h2>
        <p>Have questions or want to place an order? Reach out to us at:</p>
        <p>Email: info@bloomhaven.com</p>
        <p>Phone: (123) 456-7890</p>
    </section>
    <footer>
        <p>&copy; 2024 Bloom Haven. All rights reserved.</p>
    </footer>
</body>
</html>
